title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Ryuta Arisaka 

domain: ""
baseurl: ""

github_username: ryutaAri
github_repo: ai-deadlines-experiments

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
